### ISSUE TITLE
problems with pyms.bandpass_filter 

### ISSUE THREAD

**Issue by horsto** [magland/mountainlab#178]
I am eager to replicate the example analysis pipeline under mountainlab/packages/pymountainsort/examples/example1/example1.sh with my own data. I was able to successfully extract the timeseries from a .dat file and I am now running: 
```
mp-run-process pyms.bandpass_filter --timeseries=path_to_mda --timeseries_out=path_to_mda_bandpass --samplerate=48000 --freq_min=300 --freq_max=7000 --freq_wid=1000
```
(the file has 4 channels, 30 minutes recording) 

I however get this error message: 
```
Traceback (most recent call last):
  File "/home/hotte/mountainlab/packages/pymountainsort/basic/basic.py", line 25, in <module>
    if not PM.run(sys.argv):
  File "/home/hotte/mountainlab/packages/pymountainsort/mlpy/processormanager.py", line 35, in run
    return P(**args)
  File "/home/hotte/mountainlab/packages/pymountainsort/basic/p_bandpass_filter.py", line 51, in bandpass_filter
    if not TCR.run(timeseries,_kernel):
  File "/home/hotte/mountainlab/packages/pymountainsort/common/timeserieschunkreader.py", line 27, in run
    M,N = X.N1(),X.N2()
AttributeError: 'str' object has no attribute 'N1'
```
Can you fix that?

**Comment by magland** [comment]
Sorry my last fix broke this. Should be fixed now. please test.

**Comment by horsto** [comment]
New error: 
```
 mp-run-process pyms.bandpass_filter --timeseries=/mnt/L/horsto/raw_test/01102017/test_74471.mda --timeseries_out=/mnt/L/horsto/raw_test/01102017/test_74471_bp.mda --samplerate=48000 --freq_min=300 --freq_max=7000 --freq_wid=1000
2017-10-09:21-45-00-722 mproc.processormanager  warning "Potential problem with executable processor file: /home/hotte/mountainlab/cpp/mlcommon/src/../../../packages/pymountainsort/synthesis/synthesis.mp. Expected json output but got empty string."
2017-10-09:21-45-00-722 mproc.processormanager  warning "Executable processor file did not return output for spec: /home/hotte/mountainlab/cpp/mlcommon/src/../../../packages/pymountainsort/synthesis/synthesis.mp"
2017-10-09:21-45-01-439 mproc.processormanager  warning "Potential problem with executable processor file: /home/hotte/mountainlab/cpp/mlcommon/src/../../../packages/pymountainsort/synthesis/synthesis.mp. Expected json output but got empty string."
2017-10-09:21-45-01-441 mproc.processormanager  warning "Executable processor file did not return output for spec: /home/hotte/mountainlab/cpp/mlcommon/src/../../../packages/pymountainsort/synthesis/synthesis.mp"
RUNNING pyms.bandpass_filter: python3 /home/hotte/mountainlab/packages/pymountainsort/basic/basic.py pyms.bandpass_filter --timeseries=/mnt/L/horsto/raw_test/01102017/test_74471.mda --timeseries_out=/mnt/L/horsto/raw_test/01102017/test_74471_bp.mda --freq_max=7000 --freq_min=300 --freq_wid=1000 --samplerate=48000 --_tempdir=/mnt/DATA/temp/mountainlab/tmp_short_term/tempdir_U5DU8ODL64
Processing chunk (0%)...
Unable to support DiskWriteMda N1 2 != 4
Using 4 threads ---

2017-10-09:21-45-03-887 mproc.main      warning
2017-10-09:21-45-03-890 mproc.main      warning Process returned with non-zero exit code (255): pyms.bandpass_filter (Elapsed: 2.42 sec)

```

**Comment by magland** [comment]
Could we take this up on the slack page?

**Comment by horsto** [comment]
Yes of course! Which channel? I'll be there.
